project_id = "pspkuuiqkiyjtewixoxz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_max_part_size = "5MiB"
s3_part_expiration = 604800
image_transformation_enabled = true

[functions]
enabled = true
port = 54325

[functions.process-emergency-description]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.realtime-chat]
verify_jwt = false