// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pspkuuiqkiyjtewixoxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcGt1dWlxa2l5anRld2l4b3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQ1ODIsImV4cCI6MjA2ODM1MDU4Mn0.jZIUCtSk37wTOrWUC9uhUa6wnLTLn2xYG6I1WhoqeMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});